// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzM_cLHjGZRDQz1cZi3lKf85spJ5MR8bk',
    appId: '1:624128819913:web:99112fff37a5e9d98ec318',
    messagingSenderId: '624128819913',
    projectId: 'ankatolon',
    authDomain: 'ankatolon.firebaseapp.com',
    storageBucket: 'ankatolon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBASiydvig1cR4B5FTAuXQwzrXvGJCYT4',
    appId: '1:624128819913:android:f3e9a207bf7fe3638ec318',
    messagingSenderId: '624128819913',
    projectId: 'ankatolon',
    storageBucket: 'ankatolon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9xuDViYRZiaVA0Hq-gsNQAovBPLuxOWY',
    appId: '1:624128819913:ios:0b75b694f9231ea58ec318',
    messagingSenderId: '624128819913',
    projectId: 'ankatolon',
    storageBucket: 'ankatolon.firebasestorage.app',
    iosBundleId: 'com.example.tolon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9xuDViYRZiaVA0Hq-gsNQAovBPLuxOWY',
    appId: '1:624128819913:ios:0b75b694f9231ea58ec318',
    messagingSenderId: '624128819913',
    projectId: 'ankatolon',
    storageBucket: 'ankatolon.firebasestorage.app',
    iosBundleId: 'com.example.tolon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzM_cLHjGZRDQz1cZi3lKf85spJ5MR8bk',
    appId: '1:624128819913:web:8084aa17cfbe49c58ec318',
    messagingSenderId: '624128819913',
    projectId: 'ankatolon',
    authDomain: 'ankatolon.firebaseapp.com',
    storageBucket: 'ankatolon.firebasestorage.app',
  );
}
